mutation createSession($name: String!, $expiryDurationSeconds: Int, $allowedOrigins: String!) {
    createSession(session: { name: $name, expiryDurationSeconds: $expiryDurationSeconds, allowedOrigins: $allowedOrigins }) {
        token
        session {
            id
            referenceExpiryDate
            allowedOrigins
        }
    }
}
