mutation createSession($name: String!, $expiryDurationSeconds: Int, $originRestriction: String!) {
    createSession(session: { name: $name, expiryDurationSeconds: $expiryDurationSeconds, originRestriction: $originRestriction }) {
        token
        session {
            id
            referenceExpiryDate
            originRestriction
        }
    }
}
