query getSessions {
    system {
        auth {
            sessions {
                id
                createdAt
                createdBy
                referenceExpiryDate
                referenceTokenId
                isUserCreated
                name
                revokedAt
                allowedOrigins
            }
        }
    }
}
