query getSessions {
    sessions {
        id
        createdAt
        createdBy
        referenceExpiryDate
        referenceTokenId
        isUserCreated
        name
        revokedAt
        allowedOrigins
    }
}
