query switchboard_getSessions {
    switchboard_sessions {
        id
        createdAt
        createdBy
        referenceExpiryDate
        referenceTokenId
        isUserCreated
        name
        revokedAt
        allowedOrigins
    }
}
