replicaCount: 1

image:
  repository: ghcr.io/sidestream-tech/switchboard/api
  tag: main
  pullPolicy: IfNotPresent

imageCredentials:
  password:

volumes: []

volumeMounts: []

commitShortSHA: 2ec84b6

service:
  type: ClusterIP
  annotations: {}
  ports:
    http:
      port: 3000
  healthcheck:
    enabled: true
    path: /healthz
  env:
    - name: "AUTH_SIGNUP_ENABLED"
      value: "1"
    - name: "JWT_EXPIRATION_PERIOD_SECONDS"
      value: "3600"

podAutoscaler:
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

oauth2:
  enabled: false

ingress:
  enabled: true
  class: nginx
  certManager:
    enabled: true
    issuer: cloudflare-issuer
  timeoutEnabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
  - url: main.switchboard.k8s.sidestream.tech
    path: /api/(.*)
    tlsSecretName: switchboard-api-ingress-crt

resources:
  limits:
    cpu: 600m
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 1Gi

secrets:
  name: switchboard-api-staging-secrets
  data:
    database_url: postgres://postgres:postgres@postgresql:5432/postgres?sslmode=disable
    jwt_secret:
