replicaCount: 1

image:
  repository: ghcr.io/sidestream-tech/switchboard/frontend
  tag: main
  pullPolicy: IfNotPresent

imageCredentials:
  password:

volumes: []

volumeMounts: []

commitShortSHA: 2ec84b6

service:
  type: ClusterIP
  annotations: {}
  ports:
    http:
      port: 3000
  healthcheck:
    enabled: true
    path: /api/healthz
  env:
    - name: "AUTH_ORIGIN"
      value: "https://main.switchboard.k8s.sidestream.tech"

podAutoscaler:
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

oauth2:
  enabled: true

ingress:
  enabled: true
  class: nginx
  certManager:
    enabled: true
    issuer: cloudflare-issuer
  timeoutEnabled: false
  annotations: {}
  hosts:
  - url: main.switchboard.k8s.sidestream.tech
    path: /
    tlsSecretName: switchboard-frontend-ingress-crt

resources:
  limits:
    cpu: 600m
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 1Gi

secrets:
  name: switchboard-frontend-staging-secrets
  data:
    jwt_secret:
